### ISSUE TITLE
[Enhancement] Sub album ordering per album

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#1358]
We currently can decide per album which ordering is used for the photos.
It would be convenient to have the same option for the sub albums.

## TODO:
- [x] : add settings per album to take over default behavior when set.
- [x] : Use Sorting decorator over the Collection of children.
- [x] : Add UI to allow to change such settings
- [ ] : ~~Add API end point (with validation) to allow to change such settings.~~
