### ISSUE TITLE
[Enhancement] Make it possible to fetch random image without needing to be public & starred

### ISSUE THREAD

**Issue by mingan666** [LycheeOrg/Lychee#1814]
Make it configurable if the random method should include all accessible photos.

**Comment by ildyria** [comment]
### Todo List for anyone interested in giving it a go: 
t
- [ ] : Modify https://github.com/LycheeOrg/Lychee/blob/master/app/Http/Controllers/PhotoController.php#L78
- [ ] : Add configuration support, see here for an example of _how to_: https://github.com/LycheeOrg/Lychee/blob/master/database/migrations/2023_04_05_150625_queue-processing.php
  Use `php artisan make:migration AddRandomPhotoSettings` to generate the migration.
- [ ] : Use `Config::getValueAsBool('setting_name')` to retrieve the configuration or `Config::getValueAsString('setting_name')` depending of the choice done.

#### Optional:

- [ ] : make the album_id configurable too (Default setting should be **starred** (to preserve current behaviour):
  - `''` => all pictures
  - `'starred'` => get random picture from Starred Album (use AlbumFactory to retrieve it)
  - `'any other id'` => get random picture from selected Album (use AlbumFactory to retrieve it)
  

### IMPORTANT

- Security considerations: Visibility/Accessibility query filters should be applied so that no non-public pictures are visible.

**Comment by haivala** [comment]
I f I want to use album ids how does it actually work? Like where I can find said id and what to type in the setting?

In any case it would be nice to be able to have starred and album ids as I'm now using the starred one.

**Comment by mingan666** [comment]
Hi!

If you do not change the configuration, the system will continue to use the starred album to choose the random items
(the is the default configured album to use).

If you want another album, you need to update the settings (setting -> more -> "random_album_id") and change it to the album id you want to use (could either be a random id for the album or a string such as "starred" for a smart album). The id can be found as part of the album url.

**Comment by haivala** [comment]
Hi! 

Thank you!

In my case it would be nice to be able to choose starred and an array of albums.
and just FYI: I was looking for this setting in album info when I was not logged in as admin because it would have been natural place for it. (include in random api or similar)
