### ISSUE TITLE
[Enhancement] Allow setting copyright per picture/album.

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#1838]
### Discussed in https://github.com/LycheeOrg/Lychee/discussions/1837

<div type='discussions-op-text'>

<sup>Originally posted by **elschman** May 14, 2023</sup>
Hi,
we (sports club) do have a couple (4,500) of pictures taken from several different photographs. All are in Lychee at our own webspace but we do not own the copyright but we have to state the copyright per picture together with the picture.
Is there any supported way to fulfil this request ?</div>

## TODO

- [ ] : Create field in the base_album table
- [ ] : Add returned filed to AlbumResource
- [ ] : Display field in Front-end
- [ ] : Add editing possibility in Front-end
- [ ] : Add end point for editing copyright in Backend.

- [ ] : Same as above for Photo if per photo integration is considered.
