### ISSUE TITLE
[Enhancement] UX improvement - provide album cover placeholder when the actual cover is being downloaded

### ISSUE THREAD

**Issue by pawelmalak** [LycheeOrg/Lychee#2258]
Every time we open albums view/grid we get this flash of "unstyled content" - default album covers. It takes a while to load all of them, even on local network. With lots of albums, you can see as they get populated one by one.

![lychee](https://github.com/LycheeOrg/Lychee/assets/24780509/ff5675aa-cf99-4d9c-ae6f-1d55c778aa86)

This feature request proposes to provide simplified version of album cover with the initial albums data, so they can get rendered with the album grid. This can be achived by storing cover thumbnail in base64 format or by using something like [blurhash](https://github.com/woltapp/blurhash).

This is how it looks in the [photoview](https://github.com/photoview/photoview) app. They use it for photos in the album but the same approach can be used for the album covers. 

![photoviewblur](https://github.com/LycheeOrg/Lychee/assets/24780509/2a8ca20a-9dc7-4d65-91d8-adb8de2f8e70)

Updating album cover should also update its placeholder.

**Comment by ildyria** [comment]
### Todo:

- [ ] : add blur_hash column to size_variants
- [ ] : add step to generate blur_hash from thumb & small
- [ ] : add console command to generate blur_hash from already existing images
- [ ] : add diagnostic info check to count number of blur_hash missing
- [ ] : insert blur_hash in thumbnail 

### Questions

- [ ] : add JS decoding implementation ??
- [ ] : compute base64 image & store it in DB (replace blur_hash) ??

**Comment by aSouchereau** [comment]
Interested in this...

Looking into it, computing our own base64 images is doable, the trade off being efficiency. In manual testing I was able to reduce an image to around 100B by down-scaling to 16x16 and converting to webp (32x32 at ~135B would be better for higher fidelity and colours). I think this would be acceptable, it would require hundreds of thumbnails to make any significant impact on page load. Compared to blurhash which is only 20-30B and similar quality. However, to address the additional size, we could add a config option to disable the placeholders altogether, for those who need it.

The only downsides to Blurhash I can think of is the decoding implementation v.s. base64 being handled directly by the browser and that it would require separate dependencies for [encoding](https://github.com/kornrunner/php-blurhash) / [decoding](https://github.com/mad-gooze/fast-blurhash).

I'm willing to implement either option, whatever we decide is best.

**Comment by ildyria** [comment]
> Looking into it, computing our own base64 images is doable, the trade off being efficiency. In manual testing I was able to reduce an image to around 100B by down-scaling to 16x16 and converting to webp (32x32 at ~135B would be better for higher fidelity and colours). I think this would be acceptable, it would require hundreds of thumbnails to make any significant impact on page load. Compared to blurhash which is only 20-30B and similar quality. However, to address the additional size, we could add a config option to disable the placeholders altogether, for those who need it.
> 
> The only downsides to Blurhash I can think of is the decoding implementation v.s. base64 being handled directly by the browser and that it would require separate dependencies for [encoding](https://github.com/kornrunner/php-blurhash) / [decoding](https://github.com/mad-gooze/fast-blurhash).
> 
> I'm willing to implement either option, whatever we decide is best.

I am currently in the middle of rewriting the front-end. See #2504 and #2485.

If you integrate this in the backend, I will make it in the front-end.
Either of the option is fine with me and I do agree with the disabling config.

Implementation specific, I would consider adding that as an SizeVariant with index 7 
(see [SizeVariantType](https://github.com/LycheeOrg/Lychee/blob/master/app/Enum/SizeVariantType.php) and [SizeVariant](https://github.com/LycheeOrg/Lychee/blob/master/app/Models/SizeVariant.php)).
In both case, the short_path should be either the hash or base64 string (assuming the later fits in the DB).

**Comment by ildyria** [comment]
Done well by @aSouchereau
