### ISSUE TITLE
[Tracking] Release v4

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee#480]
Tracking the release of Lychee v4

- [x] Make sure the upgrade path for v3 is clear
- [x] Rename v3 repo
- [x] Add a link and explanation to the v3 README
- [x] Add a link and explanation to the v3 GH description
- [x] Add a note/link to v4 README for users expecting v3 at that URL
- [x] Rename v4 repo
- [x] Update v4 URLs in source
- [x] Release v4
- [x] :partying_face: :balloon: :tada: :cake: :birthday: 
- [ ] Update source URLs in Docker image.

- [ ] (Optional) At some point, Archive the v3 repo
- [ ] (Optional) Consider renaming docker repo

**Comment by ildyria** [comment]
Boum !

**Comment by privong** [comment]
A quick question, this upgrade document says to clone the `Lychee-Laravel` repo, but am I correct in understanding that it has now been renamed to `Lychee`?
https://github.com/LycheeOrg/Lychee/wiki/Upgrade-from-version-3

**Comment by d7415** [comment]
> A quick question, this upgrade document says to clone the `Lychee-Laravel` repo, but am I correct in understanding that it has now been renamed to `Lychee`?
> https://github.com/LycheeOrg/Lychee/wiki/Upgrade-from-version-3

Good spot. I'll fix that, but if you do follow those instructions it will still work - GitHub redirects from the old name. [Edit: I half fixed it. The new repo having a different name is helpful from an upload perspective.]

Aside: As this is for tracking, I'm locking this.

**Comment by d7415** [comment]
Opened separate issues for the Docker-related items in that repo as LycheeOrg/Lychee-Laravel-Docker#38 and LycheeOrg/Lychee-Laravel-Docker#39. Closing this one.
