### ISSUE TITLE
[Enhancement] Front-End on Livewire - Tracking advancement.

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#845]
## TODO

- [ ] layouts (justified etc)
- [x] image view
- [ ] Upload
- [ ] side panel
- [ ] modals for albums (delete, share, new)
- [ ] modals for pictures (delete, share)
- [x] Basic settings view
- [x] Diagnostics view
- [x] Log view
- [x] U2F view
- [x] User view
- [x] Advanced setting view
- [ ] Modules view (improved settings)
- [ ] Context menus
- [ ] Hot keys for shortcuts
- [x] Admin login/password first query on install

## Expectations and Questions

- **Required:** seamless change from current front-end to Livewire = practically invisible to the user (but may induce minor loss of functionality).
- **Question:** Do we leave the JS version still available as a setting and freeze it like for the v3?
- **Question:** ~~Do we release the livewire first as a Beta functionality that is *Opt-in*? That way the refactoring can be propagated through the back-end without stopping new (hypothetical/hopeful :sweat_smile:) development of Lychee.~~ **Yes**.

**Comment by ildyria** [comment]
https://www.youtube.com/watch?v=ELvpenyp-ak

**Comment by ildyria** [comment]
Closing this as https://github.com/LycheeOrg/Lychee/pull/1303 provides better info
